#!/bin/bash

# Check if folder argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <folder_name>"
    exit 1

fi

# Log in to the Git repository
git config --global user.email "{$CREDENTIALS_USR}"
git config --global user.name "{$CREDENTIALS_PSW}"
git config --global credential.helper 'cache --timeout=3600'
echo -n "x-access-token:$GIT_TOKEN" | base64 -w0 | git credential-store store

# Take the first argument as folder name
folder_name="$1"
folder_path="inventory/$folder_name"

# Step 1: Delete folder
rm -rf "$folder_path"
git add .
git commit -m "Deleted folder $folder_path"

# ... Rest of the script


# Step 5: Open a pull request
# Note: You might need to do this manually via your Git hosting platform (e.g., GitHub, GitLab, etc.)

